# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\pythonProject1\modes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon, QPixmap


def Mode(self, MainWindow):
    MainWindow.setObjectName("MainWindow")
    centralwidget = QtWidgets.QWidget(MainWindow)
    centralwidget.setObjectName("centralwidget")
    gridLayout_4 = QtWidgets.QGridLayout(centralwidget)
    gridLayout_4.setObjectName("gridLayout_4")
    frame = QtWidgets.QFrame(centralwidget)
    frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame.setFrameShadow(QtWidgets.QFrame.Raised)
    frame.setObjectName("frame")
    gridLayout = QtWidgets.QGridLayout(frame)
    gridLayout.setObjectName("gridLayout")
    pushButton = QtWidgets.QPushButton(frame)
    pushButton.setObjectName("pushButton")
    pushButton.setMinimumSize(QtCore.QSize(80, 40))
    pushButton.setIconSize(QSize(50, 30))
    gridLayout.addWidget(pushButton, 0, 0, 1, 1)
    gridLayout_4.addWidget(frame, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
    frame_2 = QtWidgets.QFrame(centralwidget)
    frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_2.setObjectName("frame_2")
    gridLayout_3 = QtWidgets.QGridLayout(frame_2)
    gridLayout_3.setObjectName("gridLayout_3")
    gridLayout_2 = QtWidgets.QGridLayout()
    gridLayout_2.setObjectName("gridLayout_2")
    pushButton_3 = QtWidgets.QPushButton(frame_2)
    pushButton_3.setMaximumSize(QtCore.QSize(300, 100))
    pushButton_3.setObjectName("pushButton_3")
    gridLayout_2.addWidget(pushButton_3, 0, 0, 1, 1)
    pushButton_4 = QtWidgets.QPushButton(frame_2)
    pushButton_4.setMaximumSize(QtCore.QSize(300, 100))
    pushButton_4.setObjectName("pushButton_4")
    gridLayout_2.addWidget(pushButton_4, 1, 0, 1, 1)
    gridLayout_3.addLayout(gridLayout_2, 0, 0, 1, 1)
    gridLayout_4.addWidget(frame_2, 1, 0, 1, 1)
    frame_3 = QtWidgets.QFrame(centralwidget)
    frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
    frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    frame_3.setObjectName("frame_3")
    gridLayout_4.addWidget(frame_3, 2, 0, 1, 1)
    MainWindow.setCentralWidget(centralwidget)
    MainWindow.setWindowTitle("Магический квадрат")
    pushButton.setIcon(QIcon('C:/Users/Admin/PycharmProjects/pythonProject1/menu.ico'))
    pushButton_3.setText("Магический")
    pushButton_4.setText("Полумагический")
    pushButton_3.clicked.connect(lambda: num_of_butt(self))
    pushButton_4.clicked.connect(lambda: num_of_butt(self))
    pushButton.clicked.connect(self.__init__)

def num_of_butt(self):
    self.mode = ''
    if (self.sender()).text() == 'Магический':
        self.mode = 'Magic'
        self.x = 2
        self.y = 4
    else:
        self.mode = 'Semi-magic'
        self.x = 3
        self.y = 3
    self.difficulty()

